# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-18 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['created'], 'verbose_name_plural': 'Блоги'},
        ),
    ]
