# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-18 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_auto_20170718_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='videourl',
            field=models.URLField(default=None, max_length=250, verbose_name='Видео url'),
        ),
    ]
