# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Категории')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
