# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Запись')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='entry',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Category'),
        ),
    ]
