# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-28 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20170925_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='categories',
            new_name='category',
        ),
    ]
